<?php
// SPDX-License-Identifier: GPL-3.0-only
declare(strict_types=1);

namespace DAoCCMS\Setup;

use RuntimeException;

class Writer
{
    public function writeConfig(string $path, array $data): void
    {
        $content = "<?php\n";
        $content .= "/**\n";
        $content .= " * DAoC CMS Configuration\n";
        $content .= " * Generated by Setup Wizard\n";
        $content .= " */\n\n";

        $content .= "define('SITE_URL', '" . addslashes($data['base_url']) . "');\n";
        $content .= "define('INSTANCE_ID', '" . addslashes($data['instance_id']) . "');\n";
        $content .= "define('ALDRAN_PEPPER', '" . addslashes($data['pepper']) . "');\n";
        $content .= "define('ALDHRAN_PEPPER', '" . addslashes($data['pepper']) . "');\n";
        $content .= "define('ASP_KEY', '" . addslashes($data['asp_key']) . "');\n\n";
        $content .= "define('BOT_BOOTSTRAP_SECRET', '" . addslashes($data['bot_bootstrap_secret']) . "');\n\n";

        $content .= "define('DB_HOST', '" . addslashes($data['db_host']) . "');\n";
        $content .= "define('DB_USER', '" . addslashes($data['db_user']) . "');\n";
        $content .= "define('DB_PASS', '" . addslashes($data['db_pass']) . "');\n";
        $content .= "define('DB_NAME', '" . addslashes($data['db_name']) . "');\n\n";

        $content .= "// --- Mail Configuration ---\n";
        $content .= "define('RESEND_API_KEY', '" . addslashes($data['resend_key']) . "');\n";
        $content .= "define('SMTP_FROM_EMAIL', '" . addslashes($data['sender_email']) . "');\n";
        $content .= "define('SMTP_FROM_NAME', '" . addslashes($data['sender_name']) . "');\n";

        $bytesWritten = @file_put_contents($path, $content);

        if ($bytesWritten === false) {
            throw new RuntimeException('Failed to write configuration file to ' . $path);
        }
    }
}
